### ISSUE TITLE
User Story 1: Create Homepage

### ISSUE THREAD

**Issue by JoergWolff** [JoergWolff/capstone-project#1]
## Value Proposition

**As a** User  
**I want** to be able to see my own books,  
**so that** I can get an overview of them.  

## Description

![us1](https://user-images.githubusercontent.com/117645489/213440571-10c36f67-0577-4b7f-9fe6-71acc451c71f.png)

## Acceptance Criteria

- [ ] The app title is displayed on the top left side
- [ ] A book counter is displayed on the top right side
- [ ] All books from a static JSON are displayed on the homepage
- [ ] Each book is shown on a card.
- [ ] The card displays the cover of a book.
- [ ] If the image url is empty a static image is displayed.
- [ ] The card displays the author of the book.
- [ ] The card displays the title of the book.
- [ ] The card displays the subtitle, if book is a serial.
- [ ] If the subtitle is empty, nothing is displayed.

## Tasks

- [ ] Create a static JSON file with "id", "authorId", "title", "subtitle", "image", "place", "isActive"
      "and some more form openlibary.org-api". Also think about a places JSON-file for later use.
- [ ] Import this JSON file as "initialData" to the _app.js and add this as a "data" prop to the Component of Next.
- [ ] Create a component for the head. It includes a h1 element for
      the title of the app and a span element for a counter.
- [ ] This component uses a prop {bookcounter} which is used in a
      span element. Add it to the _app.js.
- [ ] Create a component for the card to display small informations.
- [ ] This component uses the props {coverimage, author, title, subtitle}
- [ ] In the card create an IMAGE-element with next/js.
- [ ] In this component the author is displayed in a h2 element.
- [ ] In this component the title is displayed in a h3 element.
- [ ] In this component the subtitle is only displayed in h3 element, if is not empty.
- [ ] The HomePage use a prop {data}
- [ ] By mapping over the data each time a card is displayed.

## Complexity

XXL

**Comment by Long-HaHoang** [comment]
Willst du counter oben rechts mit in die user story nehmen? 
Weil die wurde nicht erwähnt.

**Comment by mbosselmann** [comment]
Hi Jörg,
we really like your first user story! We have some remarks for you that we present sorted by each section of your user story:

**Acceptance criteria**
- we miss the following criteria:
1. app title is displayed
2. book count is displayed

**Tasks**
- "Create a component for the **header**. It includes a h1 element for
the title of the app and a label element for a counter."
- "This component use a prop {bookcounter} which is used in the
label." We think a better html element could be span or output
- We think that you do not need a list component, only for the item itself
- it could be more semantic if you use elements like headings, description list or something else for author, title and sub as a paragraph is more suited for something like a description or any other longer text
- you should remove "..."

Aaaaaand: You may think about a descriptive title for this user story in addition to the user story number.

If you have questions, feel free to ask us! After editing your user story, please post the user story again in our thread. :)

**Comment by JoergWolff** [comment]
Thanks for comments. I'm not sure to change "User Story 1". Can i do that?

Also change the following:
- The App-Title is displayed on the top left side
- A book counter is displayed on the top right side
- Change label element to span
- The author, title and subtitles should be displayed in <h2> and <h3>.
- removed "..."

**Comment by mbosselmann** [comment]
Hi Jörg,
You can change the title and as far as I see, you already did that and the new title is good! 👍 Your user story looks good now, there are just some typos and I think a formatting issue:

**Acceptance criteria**
- "The **app title** is displayed on the top left side"
- "All books from a static JSON are displayed on the home page"
- "Each book is shown **on** a card."
- "The card display**s** the cover of a book." (same for the next sentences)

**Tasks**
- "This component **uses** a prop {bookcounter} which is used in the
span element."
- "This component **receives the** props {author, title, subtitle}"
- The word "tag" is now formatted as heading. That is quite confusing and should be changed.

Please try to reduce your typos for your next user story and look out for the correct formatting. Maybe **deepl** is an useful tool for you to do this and a tool I also really like ;).
However, as everything else is alright, I will approve your first user story! 🚀 

Happy hacking! :octocat:

**Comment by JoergWolff** [comment]
Thanks for helping. Reading English is easier than writing and speaking. I do my best.
I have updated all of your comments.
