### ISSUE TITLE
User Story 6: Changing the data storage

### ISSUE THREAD

**Issue by JoergWolff** [JoergWolff/capstone-project#10]
## Value Proposition

**As a** User
**I don't want to** to lose my data  
**so that** i can reach them from anywhere.  

## Description

The user's data should no longer be stored locally on the respective computer or cell phone. The obvious function of the app should not change. If the device fails or the local storage is deleted, the data should remain available. In addition, the user should be able to edit his data on another device as usual. The connection to an external database should make this possible. 

## Acceptance Criteria

- [ ] The user likes to use the app as usual.
- [ ] The user also gets his data displayed on another device.
- [ ] No data is lost.

## Tasks

- [ ] Create an external database at Mongo DB.
- [ ] Create a database connection.
- [ ] Create an API to communicate with the database.
- [ ] The API should be able to execute all CRUD commands with the database.
- [ ] Change all functions for data exchange via API.

## Complexity

XXL

**Comment by SaschaRadojkovic** [comment]
nice US  but you are aware that without different users, everybody can change the data that are saved. i think you are ;) and don't forget the models and the .env.local

**Comment by JoergWolff** [comment]
Thanks for the hints Sascha, but a user management would inflate the US but very much. I will probably install a fake account.
