### ISSUE TITLE
User Story 7: Search for book information

### ISSUE THREAD

**Issue by JoergWolff** [JoergWolff/capstone-project#15]
## Value Proposition

**As a** User 
**I want to** search for books  
**so that** I can capture or update my books faster.

## Description

![us7](https://user-images.githubusercontent.com/117645489/218061321-64a103f0-521d-41a6-922a-7bcf4c276e85.png)

## Acceptance Criteria

- [ ] The user can search for book information.
- [ ] Either the user can update already created entries with search data.
- [ ] Or the user can find new books faster.
- [ ] The user has a search form.
- [ ] The user can enter either author and title in the search form.
- [ ] Or the user can enter an ISBN in the search form.
- [ ] The user can search either with Google or with Openlibary.
- [ ] After clicking Search, the result will be displayed in the new form.
- [ ] There the user can still change his search or save it right away.

## Tasks

- [ ] Create a search link styled like a button on the new page.
- [ ] The link leads to the search page.
- [ ] Create a new page called Search.
- [ ] It displayed the Top and the Navigation component.
- [ ] Create a new component for the search.
- [ ] Add two buttons for searching.
- [ ] Add a form to this component.
- [ ] It includes a text input for the author.
- [ ] It includes a text input for the title.
- [ ] It includes a text input for the ISBN.
- [ ] Create a search api for Google and Openlibary respectively.
- [ ] Create functions to handle the form data with the APIs.
- [ ] Create a Local Storage to temporarily store the data for the new form.

## Complexity

XXL

**Comment by minatimar** [comment]
lgtm happy hacking 🦦
