### ISSUE TITLE
User Story 2: Create Detail Page

### ISSUE THREAD

**Issue by JoergWolff** [JoergWolff/capstone-project#2]
## Value Proposition

**As a** User  
**I want to** look at details of my cards  
**so that** I can read a short story to remember me 

## Description

![us2](https://user-images.githubusercontent.com/117645489/213707475-acee1ba5-95b5-47fb-9c2a-201dfb3b01f9.png)

## Acceptance Criteria

- [ ] On the home page each card component has a link to its detail page.
- [ ] The detail page displayed the app header component with the app title and the counter.
- [ ] The detail page displayed the card component with the picture, author, title and subtitle.
- [ ] The detail page displayed the internal id.
- [ ] The detail page displayed a short story of the book.
- [ ] On the bottom user can go back to the home page.

## Tasks

- [ ] Create a link styled like a button on the card component.
- [ ] Create a new details page.
- [ ] Let refer the link on the card component to the details page.
- [ ] Add the card component to the page, without showing the detail link.
- [ ] Create a details component with the props id and teaser.
- [ ] Create an id component with the prop id.
- [ ] Create a label element for the text "ID".
- [ ] Create a span element which shows the prop id.
- [ ] Add the id component to the details component.
- [ ] Create a label element with the text "Teaser:" to the details component.
- [ ] Create an article element which shows the teaser prop.
- [ ] Create a footer component.
- [ ] Add a link styled like a button to the left of this component. It directs to the home page,

## Complexity

X

**Comment by JoergWolff** [comment]
Task were written twice time. Delete one

**Comment by F-Kirchhoff** [comment]
This is a user story from the text book. LGTM 🦊 
(instead of short story you can use "summary")

**Comment by JoergWolff** [comment]
Thanks for reviewing. I'm not sure of summary. Open-libary-api is very confusing. It looks like a teaser.
