### ISSUE TITLE
User Story 3: Create Edit Page

### ISSUE THREAD

**Issue by JoergWolff** [JoergWolff/capstone-project#4]
## Value Proposition

**As a** User 
**I want to** edit details  
**so that** I can make changes of my book

## Description

![us3](https://user-images.githubusercontent.com/117645489/215317289-dc8acd38-feb9-427c-83d4-a141170084ea.png)

## Acceptance Criteria

- [ ] On the detail page at the right of the bottom a link to the edit page is displayed.
- [ ] On the edit page user can edit author, title, subtitle and teaser entries of the book.
- [ ] On the edit page at the right of the bottom a button for saving is displayed
- [ ] On the edit page at the middle of the bottom a link to the home page is displayed.
- [ ] On the edit page at the left of the bottom a link to the detail page is displayed.

## Tasks

- [ ] Create a local storage state with the content of initialData in the _app.js
- [ ] Create a function to edit a book and make changes in the local storage.
- [ ] The books and the function are passed to the props data and onEditSubmit of the Component element.
- [ ] Create a link styled like a button on the details page and add it to the footer component.
- [ ] It redirect to the new edit page.
- [ ] Create a new page called edit.js.
- [ ] The edit page use the props {data, onEditSubmit}.
- [ ] On this page use a router to find the current book.
- [ ] On this page add the top component with the title and the book counter.
- [ ] On this page the current book and the onEditSubmit prop are passed to the props book and onEditSubmit of the next created BookForm.
- [ ] Create component called BookForm.
- [ ] This component use the props {book, onEditSubmit}.
- [ ] In this component add a form element.
- [ ] In this form create an Image component with next.js.
- [ ] It displayed a dummy_book.png image, when the cover link is empty.
- [ ] Otherwise it shows the image of the cover link.
- [ ] In this form create a hidden input element for the id of the book.
- [ ] In this form create a hidden input element for the coverImg of the book.
- [ ] In this form create a label element for the author input.
- [ ] In this form create an input element, which displayed the book author.
- [ ] In this form create a label element for the title input.
- [ ] In this form create an input element, which displayed the book title.
- [ ] In this form create a label element for the subtitle input.
- [ ] In this form create an input element, which displayed the book subtitle.
- [ ] In this form create a label element for the teaser input.
- [ ] In this form create an input element, which displayed the book teaser.
- [ ] In this form create a function "handleSubmit", which read the form data.
- [ ] The data is passed to the prop onEditSubmit.
- [ ] Add this form component to the edit page.
- [ ] Add the footer component to the edit page.
- [ ] In this component create a link styled like a button on the left side.
- [ ] It redirect to the detail page.
- [ ] In this component create a link styled like a button in the middle.
- [ ] It redirect to the home page.
- [ ] In this component create a save button.
- [ ] It should save the form data and redirect to the detail page.
- [ ] It should also save the book in the local storage state.

## Complexity

XL

**Comment by mbosselmann** [comment]
Hi Jörg,
you rock! 🪨 Such a detailed and well thought out user story is incredible! 💪 This user story will definitely help you to implement the feature well. :) I also like your estimation of complexity.
In fact, I would have one more idea for a task, but I think it is already indirectly covered by your last two tasks, so I would still approve your user story. I would add that you need a handleSubmit function to save the updated book data.
And there are also some typos that you could fix. For example: "details page" and not "detail page" or "It redirect**s** to the new edit page." Feel free to correct that if you want to.

Happy hacking! :octocat:

**Comment by JoergWolff** [comment]
Thanks Mareike,
can't find the "redirects" word. It was already without "s"🙂
You are right to add a handleSubmit function.
🤘 have also thought about an addItem function for the the local storage.
