### ISSUE TITLE
User Story 4: Create New Page

### ISSUE THREAD

**Issue by JoergWolff** [JoergWolff/capstone-project#6]
## Value Proposition

**As a** User 
**I want to** create a new book
**so that** I can expand my book collection.

## Description

![us4](https://user-images.githubusercontent.com/117645489/215320908-c95a25f3-4d0b-4f3c-ba38-e123d9b805ad.png)

## Acceptance Criteria

- [ ] On the landing page at the right of the bottom a link to the new page is displayed.
- [ ] On the new page the user can create a new book.
- [ ] On the new page the user must create an author in the input field.
- [ ] On the new page the user must create a title in the input field.
- [ ] All other input fields can be filled in.
- [ ] On the new page at the right of the bottom a button for saving is displayed.
- [ ] On the new page at the middle of the bottom a link to the home page is displayed.

## Tasks

- [ ] Add the Bottom component to the bottom of the home page.
- [ ] Create a link styled like a button at the right bottom of the home page.
- [ ] It redirect to the next created new page.
- [ ] Create a new page called create.js.
- [ ] It contains the function handleSubmit.
- [ ] This function add a new book to the local storage.
- [ ] Add the BookForm component to this page.
- [ ] This gets the prop onSubmit={handleSubmit} passed to it
- [ ] Add the Bottom component to this page.
- [ ] Create on the left side a link styled like a button.
- [ ] It redirect back to the homepage.
- [ ] Create on the right side a button for saving.
- [ ] It contains the onClick event to save the new book.

## Complexity

XL

**Comment by niklasrammelkamp** [comment]
nice story. 
The only thing I have is that, if the image input is disabled you shouldn't implement it. 
I'm not sure what you wanna do later but if you wanna add a user upload you can implement the input type file later on.
Because in this Story the user has no benefit much more than a handicap by clicking something that doesn't work.

**Comment by JoergWolff** [comment]
Thanks Niklas good hint. The brain is further than the user. But the form is also used for editing in Userstory 3. I have to prevent the input, because there will be a search function to OpenLibary later. Also I didn't want to store all web pages in next.config.js. The user should not be able to change the link for now.

**Comment by niklasrammelkamp** [comment]
Okay alright, I think if it makes sense for further implementation all in all it's fine I guess :D

**Comment by JoergWolff** [comment]
Thank you for letting me convince you.
I am not sure yet how to handle the problem before.
I can only disable it for now.
