### ISSUE TITLE
User Story 5: Delete Button

### ISSUE THREAD

**Issue by JoergWolff** [JoergWolff/capstone-project#8]
## Value Proposition

**As a** User
**I want to** delete a book  
**so that** I can remove old entries.

## Description

![us5](https://user-images.githubusercontent.com/117645489/215795768-af16ee37-b265-4be8-8aab-a35faaa3eb1c.png)

## Acceptance Criteria

- [ ] On the detail page a delete button is displayed.
- [ ] When you click, a message appears asking if you want to delete.
- [ ] The user can confirm it with Ok or cancel it with Cancel.
- [ ] With Ok the entry is deleted and the user will be redirected to the home page.
- [ ] With Cancel the user will be redirected to the detail page.

## Tasks

- [ ] Create a delete button on the detail page.
- [ ] Create a handleConfirm function with a confirm statement.
- [ ] When clicking the delete button, this function is called to confirm it with Ok or Cancel.
- [ ] Press ok to delete the entry.
- [ ] Create a delete function in the _app.js.
- [ ] This function is passed to the component as a new prop.
- [ ] The detail page use this prop for deleting entry.

## Complexity

M

**Comment by janneserichsen** [comment]
Looks good to me but maybe you want to work here When you click, a message appears asking if you want to delete.
with a Alert

**Comment by JoergWolff** [comment]
Thanks...make some changes.

**Comment by janneserichsen** [comment]
Looking good to me now

**Comment by minatimar** [comment]
lgtm too :) happy hacking
